remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tarea 01. GF0657
description: Este sitio web corresponde a la asignaci칩n de la Tarea 01 para el curso de Programaci칩n en SIG (GF-0657). El contenido de la p치gina es de una previa investigaci칩n realizada para la UCR.
